# pod2man -r " " -s 1 -c gntp-send -n GNTP-SEND gntp-send.pod

=head1 NAME

gntp-send - Utility for sending notifications to Growl using UDP or GNTP protocols

=head1 SYNOPSIS

gntp-send [-u] [-a APPNAME] [-n NOTIFY] [-s SERVER:PORT] [-p PASSWORD] title message [icon] [url]

=head1 DESCRIPTION 

Sends notification to local or remote Growl application over UDP or TCP network protocols.
When the notification is sent over TCP using GNTP http callbacks and both local and remote icons are supported.
 

=head1 OPTIONS

 -a APPLICATION
	application name , defaults to gntp-send

 -n NOTIFICATION
	notification name , defaults to gntp-send notify

 -s HOST:PORT , -s HOST
	host and port to send notification to , host defaults to localhost and the port defaults to the protocol default (tcp: 23053 , udp: 9887) , you can specify the host only and the port defaults to the protocol default

 -p PASSWORD
	password , defaults to not attempting authentication

 -u
	send the notification over UDP , by default the notification is sent over TCP using GNTP

=head1 POSITIONAL ARGUMENTS

 title 
	mandatory , title of the notification

 message 	
	mandatory , notification message

 icon 	
	optional , local file name or url of icon for the notification 

 url 	
	optional , url to call if the notification is clicked 

=head1 DIAGNOSTICS

Setting the environmental variable GNTP_DEBUG will cause the TCP traffic to be printed to STDOUT

0 if the notification was delivered to Growl , this does not mean it was accepted

-1 otherwise

=head1 BUGS

None
